name: LumaCore
main: dev.jsinco.luma.lumacore.LumaCore
version: '${version}'
api-version: 1.21
author: 'Jsinco'
libraries: ['org.jetbrains.kotlin:kotlin-stdlib:2.0.21']
load: STARTUP
softdepend: [PlaceholderAPI]